version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///data/ohipforward.db
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=false
    volumes:
      - ./data:/app/data
      - .env:/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL database for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_DB=ohipforward
  #     - POSTGRES_USER=ohip
  #     - POSTGRES_PASSWORD=changeme
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data:
